---
name: Push datasets-cli

on:
  push:
    branches:
      - main
    paths:
      - src/datasets-cli/*
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_OIDC_ROLE_ARN: ${{ secrets.AWS_OIDC_ROLE_ARN }}
  DOCKER_IMAGE_GROUP: ncbi
  DOCKER_IMAGE: datasets-cli

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set shell options
        run: set -euxo pipefail

      - name: Setup qemu
        uses: docker/setup-qemu-action@v3

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_OIDC_ROLE_ARN }}
          role-session-name: aws-oidc-${{ github.repository.name }}-${{ github.run_id }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Login to AWS ECR Public Registry
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Extract Version from Dockerfile
        id: extract_version
        run: |
          DOCKER_IMAGE_TAG=v2
          echo "DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG#v}" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG#v}"

      - name: Create AWS ECR Public Repository
        run: |
          aws ecr-public create-repository --repository-name ${{ env.DOCKER_IMAGE_GROUP }}/${{ env.DOCKER_IMAGE }} --region ${{ env.AWS_DEFAULT_REGION }} || true

      - name: Docker build & push
        uses: docker/bake-action@v5
        with:
          targets: push
          workdir: ./src/${{ env.DOCKER_IMAGE }}
